import * as F from "./firebase.js";
import "./app.js";
import { uploadToCloudinary } from "./cloudinary.js";

const isClientPage=location.pathname.endsWith("client.html");
const isLogin=location.pathname.endsWith("login.html");
const msg=(id,t,good=false)=>{const e=document.getElementById(id);if(e){e.textContent=t;e.className="msg "+(good?"success":"");}};
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
let currentUser=null,currentProfile=null,currentEvents=[];
const withTimeout=(promise,ms=15000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error("انتهت مهلة الاتصال بـ Firebase. تحقق من الإنترنت وإعدادات Firebase ثم حاول مرة أخرى.")),ms))]);

async function getClientProfile(uid){const s=await F.getDoc(F.doc(F.db,"clients",uid));return s.exists()?{id:s.id,...s.data()}:null;}
function requireAuth(){F.onAuthStateChanged(F.auth,async user=>{if(isLogin){if(user){const p=await getClientProfile(user.uid);location.href=p?.role==="admin"?"admin.html":"client.html";}return;}if(!isClientPage)return;if(!user){location.href="login.html";return;}const p=await getClientProfile(user.uid);if(!p||p.active===false){await F.signOut(F.auth);location.href="login.html";return;}if(p.expiresAt&&p.expiresAt<new Date().toISOString().slice(0,10)){await F.signOut(F.auth);alert("انتهت صلاحية الحساب.");location.href="login.html";return;}currentUser=user;currentProfile=p;initClient(user,p);});}
async function clearFirebaseClientState(){try{localStorage.clear();sessionStorage.clear();if(indexedDB.databases){const dbs=await indexedDB.databases();await Promise.all(dbs.map(x=>x.name).filter(Boolean).filter(n=>/firebase|firestore|app.?check/i.test(n)).map(n=>new Promise(resolve=>{const r=indexedDB.deleteDatabase(n);r.onsuccess=r.onerror=r.onblocked=()=>resolve()})))}}catch{}}
async function login(){const form=qs("#loginForm");if(!form)return;qs("#togglePassword")?.addEventListener("click",()=>{const input=qs("#password");const visible=input.type==="text";input.type=visible?"password":"text";qs("#togglePassword").textContent=visible?"إظهار":"إخفاء"});qs("#resetFirebaseSession")?.addEventListener("click",async()=>{msg("loginMsg","جاري تنظيف جلسة Firebase...");await clearFirebaseClientState();location.reload()});form.addEventListener("submit",async e=>{e.preventDefault();const button=form.querySelector("button[type=submit]");button?.setAttribute("disabled","disabled");msg("loginMsg","جاري تسجيل الدخول...");try{await withTimeout(F.signInWithEmailAndPassword(F.auth,qs("#email").value.trim().toLowerCase(),qs("#password").value));}catch(err){msg("loginMsg",friendly(err));}finally{button?.removeAttribute("disabled")}})}
function friendly(e){const code=e?.code||"",text=String(e?.message||"");if(code==="auth/invalid-credential"||code==="auth/wrong-password"||code==="auth/user-not-found")return"البريد أو كلمة المرور غير صحيحة.";if(code==="auth/too-many-requests")return"تم إيقاف المحاولات مؤقتًا. انتظر قليلًا ثم حاول مرة أخرى.";if(code==="auth/network-request-failed")return"تعذر الاتصال بالإنترنت. تحقق من الشبكة وحاول مرة أخرى.";if(code==="auth/firebase-app-check-token-is-invalid"||code==="auth/app-check-token-is-invalid"||/app.?check.*invalid/i.test(text))return"Firebase App Check يرفض الدومين الحالي. إمّا أضف reCAPTCHA Site Key الصحيح في firebase-config-module.js مع تسجيل الدومين، أو عطّل Enforcement لـ Authentication من Firebase Console.";if(code==="auth/operation-not-allowed")return"تسجيل الدخول بالبريد غير مفعّل. فعّله من Firebase Authentication.";return text||"حدث خطأ غير متوقع."}
async function initClient(user,p){
  qs("#clientLoading")?.classList.add("hidden");qs("#clientApp")?.classList.remove("hidden");qs("#clientEmail").textContent=user.email;qs("#clientName").textContent=p.name||"";
  qs("#clientLogout")?.addEventListener("click",async()=>{await F.signOut(F.auth);location.href="login.html"});
  currentEvents=await loadEvents(user.uid);renderEvents(currentEvents);fillTemplates();bindEditor();
  qs("#createEventBtn")?.addEventListener("click",()=>openEditor());
  qs("#checkinBtn")?.addEventListener("click",openCheckin);
  updateStats(currentEvents);
}
async function loadEvents(uid){const snap=await F.getDocs(F.query(F.collection(F.db,"events"),F.where("clientId","==",uid)));return snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));}
function updateStats(events){qs("#cEvents").textContent=events.length;let guests=0,views=0,rsvp=0,checked=0;events.forEach(e=>{guests+=e.guestCount||0;views+=e.viewCount||0;rsvp+=e.rsvpCount||0;checked+=e.checkedInCount||0});qs("#cGuests").textContent=guests;qs("#cViews").textContent=views;qs("#cRsvp").textContent=rsvp;const c=qs("#cChecked");if(c)c.textContent=checked;}
function renderEvents(events){const el=qs("#eventList");if(!el)return;el.innerHTML=events.length?events.map(e=>`<article class="event-card"><div class="event-status ${e.published===false?"off":"on"}">${e.published===false?"متوقفة":"منشورة"}</div><h3>${esc(e.groomName||"")} ♡ ${esc(e.brideName||"")}</h3><p>${esc(e.venue||"")} • ${e.eventDate||""}</p><p>المعازيم: ${e.guestCount||0} • المشاهدات: ${e.viewCount||0} • الحضور: ${e.rsvpCount||0} • دخول: ${e.checkedInCount||0}</p><div class="event-actions"><button class="btn btn-gold btn-sm" data-edit="${e.id}">المحرر والإدارة</button><a class="btn btn-outline btn-sm" href="invite.html?event=${encodeURIComponent(e.id)}&preview=1" target="_blank">معاينة</a><button class="btn btn-dark btn-sm" data-publish="${e.id}">${e.published===false?"نشر الدعوة":"إيقاف الدعوة"}</button></div></article>`).join(""):`<div class="panel"><p>لا توجد دعوات بعد. ابدأ بإنشاء دعوة جديدة.</p></div>`;qsa("[data-edit]").forEach(b=>b.onclick=()=>editEvent(b.dataset.edit));qsa("[data-publish]").forEach(b=>b.onclick=()=>togglePublish(b.dataset.publish));}
function fillTemplates(){const el=qs("#templateId");if(!el)return;el.innerHTML=window.DAWATY_TEMPLATES.map(t=>`<option value="${t.id}">${t.name} — ${t.label}${t.premium?" (Premium)":""}</option>`).join("");el.addEventListener("change",updateTemplatePreview);updateTemplatePreview();}
function updateTemplatePreview(){const id=qs("#templateId")?.value,t=window.DAWATY_TEMPLATES.find(x=>x.id===id);if(!t)return;const preview=qs("#templatePreview");if(!preview)return;preview.className=`template-preview-mini ${t.family}-theme`;preview.innerHTML=`<div><b style="font-size:25px">${t.ornament}</b><div style="font-family:'Playfair Display',serif;font-size:28px">${esc(qs("#groomName")?.value||"أحمد")} ♡ ${esc(qs("#brideName")?.value||"هاجر")}</div><small>${t.name} • ${t.label}</small></div>`;updateLivePreview();}
function bindEditor(){qs("#closeEditor")?.addEventListener("click",()=>qs("#eventEditor").classList.add("hidden"));qs("#eventForm")?.addEventListener("submit",saveEvent);qs("#importGuests")?.addEventListener("click",importGuests);qs("#downloadTemplate")?.addEventListener("click",downloadXlsx);qs("#previewEvent")?.addEventListener("click",previewEvent);qs("#bridePhoto")?.addEventListener("change",()=>uploadPhoto("bridePhoto","bridePreview","brideImageUrl"));qs("#groomPhoto")?.addEventListener("change",()=>uploadPhoto("groomPhoto","groomPreview","groomImageUrl"));["groomName","brideName","inviteText","accentColor","fontFamily","cardStyle"].forEach(id=>qs("#"+id)?.addEventListener("input",updateLivePreview));}
function openEditor(e={}){qs("#eventEditor").classList.remove("hidden");qs("#eventId").value=e.id||"";qs("#groomName").value=e.groomName||"";qs("#brideName").value=e.brideName||"";qs("#eventDate").value=e.eventDate||"";qs("#eventTime").value=e.eventTime||"";qs("#venue").value=e.venue||"";qs("#venueAddress").value=e.venueAddress||"";qs("#mapUrl").value=e.mapUrl||"";qs("#brideHenna").value=e.brideHenna||"";qs("#groomHenna").value=e.groomHenna||"";qs("#templateId").value=e.templateId||qs("#templateId").value;qs("#inviteText").value=e.inviteText||"يتشرفان بدعوتكم لحضور حفل زفافهما، ووجودكم يزيد فرحتنا.";qs("#accentColor").value=e.design?.accent||"#d4af37";qs("#fontFamily").value=e.design?.font||"Cairo";qs("#cardStyle").value=e.design?.cardStyle||"classic";qs("#groomImageUrl").value=e.groomImageUrl||"";qs("#brideImageUrl").value=e.brideImageUrl||"";setPreviewImage("groomPreview",e.groomImageUrl);setPreviewImage("bridePreview",e.brideImageUrl);updateTemplatePreview();if(e.id){qs("#guestTools").classList.remove("hidden");loadGuests(e.id)}else qs("#guestTools").classList.add("hidden");window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"});}
async function editEvent(id){const s=await F.getDoc(F.doc(F.db,"events",id));if(s.exists())openEditor({id:s.id,...s.data()});}
async function saveEvent(e){e.preventDefault();const data={clientId:currentUser.uid,groomName:qs("#groomName").value.trim(),brideName:qs("#brideName").value.trim(),eventDate:qs("#eventDate").value,eventTime:qs("#eventTime").value,venue:qs("#venue").value.trim(),venueAddress:qs("#venueAddress").value.trim(),mapUrl:qs("#mapUrl").value.trim(),brideHenna:qs("#brideHenna").value,groomHenna:qs("#groomHenna").value,templateId:qs("#templateId").value,inviteText:qs("#inviteText").value.trim(),groomImageUrl:qs("#groomImageUrl").value.trim(),brideImageUrl:qs("#brideImageUrl").value.trim(),design:{accent:qs("#accentColor").value,font:qs("#fontFamily").value,cardStyle:qs("#cardStyle").value},updatedAt:F.serverTimestamp()};try{let id=qs("#eventId").value;if(id){await F.updateDoc(F.doc(F.db,"events",id),data)}else{const r=await F.addDoc(F.collection(F.db,"events"),{...data,createdAt:F.serverTimestamp(),guestCount:0,viewCount:0,rsvpCount:0,checkedInCount:0,published:true});id=r.id;qs("#eventId").value=id;qs("#guestTools").classList.remove("hidden")};await syncPublicEvent(id,data, (currentEvents.find(x=>x.id===id)?.published)!==false);msg("eventMsg","تم حفظ الدعوة بنجاح.",true);currentEvents=await loadEvents(currentUser.uid);renderEvents(currentEvents);updateStats(currentEvents);loadGuests(id)}catch(err){msg("eventMsg",friendly(err))}}
async function syncPublicEvent(id,data,published=true){await F.setDoc(F.doc(F.db,"publicEvents",id),{eventId:id,...data,published,updatedAt:F.serverTimestamp()},{merge:true});}
async function togglePublish(id){const e=currentEvents.find(x=>x.id===id);if(!e)return;const next=e.published===false;await F.updateDoc(F.doc(F.db,"events",id),{published:next,updatedAt:F.serverTimestamp()});await F.updateDoc(F.doc(F.db,"publicEvents",id),{published:next,updatedAt:F.serverTimestamp()});const gs=await F.getDocs(F.query(F.collection(F.db,"guests"),F.where("eventId","==",id),F.where("clientId","==",currentUser.uid)));for(const d of gs.docs){const g=d.data();if(g.token)await F.updateDoc(F.doc(F.db,"publicInvites",g.token),{published:next});}currentEvents=await loadEvents(currentUser.uid);renderEvents(currentEvents);updateStats(currentEvents);msg("eventMsg",next?"تم نشر الدعوة.":"تم إيقاف الدعوة.",true);}
async function uploadPhoto(fileId,previewId,urlId){const file=qs("#"+fileId)?.files?.[0];if(!file)return;try{msg("eventMsg","جاري رفع الصورة إلى Cloudinary...");const r=await uploadToCloudinary(file,`dawaty/${currentUser.uid}`);qs("#"+urlId).value=r.url;setPreviewImage(previewId,r.url);msg("eventMsg","تم رفع الصورة.",true);updateLivePreview()}catch(e){msg("eventMsg",e.message)}}
function setPreviewImage(id,url){const el=qs("#"+id);if(!el)return;el.innerHTML=url?`<img src="${esc(url)}" alt="">`:`<span>لم يتم رفع صورة</span>`;}
function updateLivePreview(){const p=qs("#liveInvitePreview");if(!p)return;const design={accent:qs("#accentColor")?.value||"#d4af37",font:qs("#fontFamily")?.value||"Cairo",cardStyle:qs("#cardStyle")?.value||"classic"};p.style.setProperty("--invite-accent",design.accent);p.style.setProperty("--invite-font",design.font);p.className=`live-invite-preview ${design.cardStyle}`;p.innerHTML=`<div class="live-photo-row"><div>${qs("#groomPreview")?.innerHTML||""}</div><div>${qs("#bridePreview")?.innerHTML||""}</div></div><div class="live-orn">❦</div><small>بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيمِ</small><h3>${esc(qs("#groomName")?.value||"أحمد")} ♡ ${esc(qs("#brideName")?.value||"هاجر")}</h3><p>${esc(qs("#inviteText")?.value||"")}</p>`;}
async function loadGuests(eventId){const snap=await F.getDocs(F.query(F.collection(F.db,"guests"),F.where("eventId","==",eventId),F.where("clientId","==",currentUser.uid)));const rows=[];for(const d of snap.docs){const g={id:d.id,...d.data()};if(g.token){const ps=await F.getDoc(F.doc(F.db,"publicInvites",g.token));if(ps.exists()){const pub=ps.data();Object.assign(g,{viewed:pub.viewed||false,rsvp:pub.rsvp||"pending",partySize:pub.partySize||0,table:pub.table||"",checkedIn:pub.checkedIn||false});}}rows.push(g)}const el=qs("#guestTable");if(!el)return;el.innerHTML=rows.map(g=>`<tr><td>${esc(g.name||"")}</td><td>${esc(g.phone||"")}</td><td>${g.viewed?"✓":"—"}</td><td>${g.rsvp==="yes"?`✓ ${g.partySize||1}`:g.rsvp==="no"?"✕":"—"}</td><td>${esc(g.table||"—")}</td><td>${g.checkedIn?"✓":"—"}</td><td><button class="btn btn-outline btn-sm" data-copy="${esc(g.token||"")}">نسخ</button> <button class="btn btn-dark btn-sm" data-wa="${esc(g.id)}">WhatsApp</button></td><td>${g.token?`<a class="btn btn-gold btn-sm" target="_blank" href="invite.html?event=${encodeURIComponent(eventId)}&token=${encodeURIComponent(g.token)}">فتح</a>`:""}</td></tr>`).join("")||`<tr><td colspan="8">لم تتم إضافة معازيم بعد.</td></tr>`;qsa("[data-copy]").forEach(b=>b.onclick=async()=>{const url=guestUrl(eventId,b.dataset.copy);await navigator.clipboard.writeText(url);b.textContent="تم النسخ"});qsa("[data-wa]").forEach(b=>b.onclick=()=>sendWhatsApp(rows.find(x=>x.id===b.dataset.wa),eventId));renderTables(rows);}
function guestUrl(eventId,token){return new URL(`invite.html?event=${encodeURIComponent(eventId)}&token=${encodeURIComponent(token)}`,location.href).href}
function sendWhatsApp(g,eventId){if(!g)return;const phone=normalizePhone(g.phone);if(!phone){alert("رقم الهاتف غير صالح.");return}const e=currentEvents.find(x=>x.id===eventId)||{};const text=`أهلاً ${g.name||""} ❤️\nنتشرف بدعوتكم لحضور حفل زفاف ${e.groomName||""} و${e.brideName||""}.\nرابط دعوتك الشخصية:\n${guestUrl(eventId,g.token)}`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,"_blank","noopener");}
function normalizePhone(v){let x=String(v||"").replace(/\D/g,"");if(x.startsWith("00"))x=x.slice(2);if(x.startsWith("01")&&x.length===11)x="20"+x;return x;}
function renderTables(rows){const wrap=qs("#tablesWrap");if(!wrap)return;const groups={};rows.forEach(g=>{const t=g.table||"بدون طاولة";(groups[t]??=[]).push(g)});wrap.innerHTML=`<div class="table-editor-head"><input id="tableName" placeholder="اسم الطاولة / رقمها"><button class="btn btn-gold btn-sm" id="addTable">إضافة</button></div><div class="table-chips">${Object.keys(groups).filter(x=>x!=="بدون طاولة").map(t=>`<span class="table-chip">${esc(t)} <b>${groups[t].length}</b></span>`).join("")}</div><p class="muted">لتعيين طاولة: استخدم زر التعيين بجوار الضيف.</p>${rows.map(g=>`<div class="seat-row"><span>${esc(g.name)}</span><select data-table-for="${g.id}"><option value="">بدون طاولة</option>${Object.keys(groups).filter(x=>x!=="بدون طاولة").map(t=>`<option ${g.table===t?"selected":""}>${esc(t)}</option>`).join("")}</select><button class="btn btn-outline btn-sm" data-save-table="${g.id}">حفظ</button></div>`).join("")}`;qs("#addTable")?.addEventListener("click",()=>{const n=qs("#tableName").value.trim();if(!n)return;const existing=[...wrap.querySelectorAll(".table-chip")].map(x=>x.textContent.replace(/\s*\d+$/,""));if(existing.includes(n))return;const e=currentEvents.find(x=>x.id===qs("#eventId").value);if(e){e.tables=[...(e.tables||[]),{name:n,capacity:0}];F.updateDoc(F.doc(F.db,"events",e.id),{tables:e.tables}).then(()=>loadGuests(e.id));}});qsa("[data-save-table]").forEach(b=>b.onclick=async()=>{const id=b.dataset.saveTable;const sel=wrap.querySelector(`[data-table-for="${id}"]`);await F.updateDoc(F.doc(F.db,"guests",id),{table:sel.value});const g=await F.getDoc(F.doc(F.db,"guests",id));if(g.exists()&&g.data().token)await F.updateDoc(F.doc(F.db,"publicInvites",g.data().token),{table:sel.value});loadGuests(qs("#eventId").value)});}
async function importGuests(){const file=qs("#guestFile").files[0],eventId=qs("#eventId").value;if(!file||!eventId){msg("importMsg","احفظ الدعوة أولًا ثم اختر ملفًا.");return}msg("importMsg","جاري قراءة الملف...");try{let rows=[];if(/\.xlsx?$|\.csv$/i.test(file.name)){await loadScript("https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js");const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:"array",cellDates:true});const sheet=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{defval:""});}else if(/\.docx$/i.test(file.name)){await loadScript("https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js");const data=await file.arrayBuffer();const out=await mammoth.extractRawText({arrayBuffer:data});rows=out.value.split(/\r?\n/).map(x=>({الاسم:x.trim()})).filter(x=>x.الاسم);}else throw new Error("نوع الملف غير مدعوم. استخدم Excel / CSV / Word.");const norm=rows.map(r=>({name:String(r["الاسم"]||r["اسم المعزوم"]||r["اسم الضيف"]||r["name"]||r["Name"]||r["guest"]||Object.values(r)[0]||"").trim(),phone:String(r["الهاتف"]||r["رقم الهاتف"]||r["الموبايل"]||r["phone"]||r["Phone"]||r["mobile"]||"").trim(),table:String(r["الطاولة"]||r["رقم الطاولة"]||r["table"]||"").trim() })).filter(x=>x.name);const profile=currentProfile;const current=await F.getDocs(F.query(F.collection(F.db,"guests"),F.where("eventId","==",eventId),F.where("clientId","==",currentUser.uid)));if(profile?.guestLimit&&current.size+norm.length>profile.guestLimit)throw new Error(`الحد المسموح ${profile.guestLimit} معزوم. الملف يحتوي ${norm.length}.`);const evSnap=await F.getDoc(F.doc(F.db,"events",eventId));const ed=evSnap.data();for(const g of norm){const token=randomToken(24);await F.addDoc(F.collection(F.db,"guests"),{eventId,clientId:currentUser.uid,name:g.name,phone:g.phone,table:g.table,token,createdAt:F.serverTimestamp()});await F.setDoc(F.doc(F.db,"publicInvites",token),{token,eventId,name:g.name,phone:g.phone,table:g.table,groomName:ed.groomName,brideName:ed.brideName,eventDate:ed.eventDate,eventTime:ed.eventTime,venue:ed.venue,venueAddress:ed.venueAddress,mapUrl:ed.mapUrl,brideHenna:ed.brideHenna,groomHenna:ed.groomHenna,templateId:ed.templateId,inviteText:ed.inviteText,groomImageUrl:ed.groomImageUrl||"",brideImageUrl:ed.brideImageUrl||"",design:ed.design||{},viewed:false,rsvp:"pending",partySize:0,checkedIn:false,published:ed.published!==false,createdAt:F.serverTimestamp()});}await F.updateDoc(F.doc(F.db,"events",eventId),{guestCount:current.size+norm.length,updatedAt:F.serverTimestamp()});msg("importMsg",`تم استيراد ${norm.length} معزوم بنجاح.`,true);loadGuests(eventId)}catch(err){msg("importMsg",err.message||"تعذر استيراد الملف.")}}
function randomToken(n){const a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"[x%62]).join("")}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement("script");s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
function downloadXlsx(){const blob=new Blob(["\uFEFFالاسم\tرقم الهاتف\tالطاولة\nمحمد علي\t01000000000\tطاولة 1\nأحمد حسن\t01100000000\tطاولة 2"],{type:"text/tab-separated-values;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="نموذج-المعازيم.xls";a.click()}
function previewEvent(){const id=qs("#eventId").value;if(!id){alert("احفظ الدعوة أولًا.");return}window.open(`invite.html?event=${id}&preview=1`,"_blank")}
async function openCheckin(){const id=qs("#eventId")?.value||currentEvents[0]?.id;if(!id){alert("أنشئ دعوة أولاً.");return}const modal=qs("#checkinModal");modal.classList.remove("hidden");qs("#checkinEventId").value=id;qs("#checkinResult").textContent="";qs("#checkinToken").value="";qs("#checkinSearch").onclick=()=>checkinByToken(id,qs("#checkinToken").value.trim());}
async function checkinByToken(eventId,token){const result=qs("#checkinResult");if(!token){result.textContent="أدخل رمز QR أو التوكن.";return}const s=await F.getDoc(F.doc(F.db,"publicInvites",token));if(!s.exists()||s.data().eventId!==eventId){result.textContent="لم يتم العثور على الضيف.";return}const g=s.data();if(g.checkedIn){result.innerHTML=`<b>تم الدخول مسبقًا</b><br>${esc(g.name)}${g.table?` — ${esc(g.table)}`:""}`;return}await F.updateDoc(F.doc(F.db,"publicInvites",token),{checkedIn:true,checkedInAt:F.serverTimestamp()});const gs=await F.getDocs(F.query(F.collection(F.db,"guests"),F.where("eventId","==",eventId),F.where("clientId","==",currentUser.uid),F.where("token","==",token)));if(!gs.empty)await F.updateDoc(gs.docs[0].ref,{checkedIn:true,checkedInAt:F.serverTimestamp()});await F.updateDoc(F.doc(F.db,"events",eventId),{checkedInCount:F.increment(1)});result.innerHTML=`<span class="success">✓ تم تسجيل الدخول</span><br><b>${esc(g.name)}</b>${g.table?`<br>الطاولة: ${esc(g.table)}`:""}`;currentEvents=await loadEvents(currentUser.uid);renderEvents(currentEvents);updateStats(currentEvents)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
login();requireAuth();
